# 公開するページのURL
baseURL = "https://yuito-it.github.io/blog/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true
publishDir = "docs"

# ブログのタイトル
title = "Yuito's Dev Blog"

googleAnalytics = "G-S01FFC4N61"

theme = "Mainroad"
paginate = 10

enableGitInfo = true

# 自己紹介
[Author]
  name = "唯人"
  bio = "神山まるごと高専を目指す、一介の中学三年生。\n ポリシーは「なんでもやってみる」"
  avatar = "img/avatar.webp"

[Params]
  description = "中学生デベロッパー、唯人の成長記と雑記帳。" 
  customCSS = ["css/custom.css"]
  copyright = "yuito-it 2023,kat0h 2021"
  readmore = true
  authorbox = true
  schema = true
  post_meta = ["date", "categories"]
  twitter_cards = true
  listPageDateFormat = "2023-08-16T15:04:05+09:00"
  singlePageDateFormat = "2023-08-16T15:04:05+09:00"
  pager = true
  opengraph = true
  # コメント用
  giscus = true
  toc = true

[Params.logo]
  image = "img/avatar.webp"
  title = "Yuito's Dev Blog"
  subtitle = "中学生デベロッパーの成長記と雑記帳"

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#bf7fff"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "yuito_it_"
  github = "yuito-it"
  telegram = "yuitoENGINEER"
  email = "yuito_it@outlook.jp"
  bitbucket = "yuito-it"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = true
        startLevel = 2
