# 公開するページのURL
baseURL = "https://yuito-it.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "Yuito's Develpment Blog"

googleAnalytics = "G-S01FFC4N61"

theme = "Mainroad"
paginate = 20

enableGitInfo = true

# 自己紹介
[Author]
    name = "唯人"
    bio = "神山まるごと高専を目指す、一介の中学三年生。\n ポリシーは「なんでもやってみる」"
    avatar = "img/avatar.webp"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "yuito-it 2023,kat0h 2021"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true
    listPageDateFormat = "2006-01-02"
    singlePageDateFormat = "2006-01-02"
    pager = true
    opengraph = true
    # コメント用
    giscus = true
    

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#bf7fff"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "yuito_it_"
  github = "yuito-it"
  telegram = "yuitoENGINEER"
  email = "yuito_it@outlook.jp"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = true
        startLevel = 2
